### PR TITLE
Fix code scanning alert no. 2: DOM text reinterpreted as HTML

### PR DESCRIPTION
**Pull request by obscurerichard**
Fixes [https://github.com/freezingsaddles/freezing-web/security/code-scanning/2](https://github.com/freezingsaddles/freezing-web/security/code-scanning/2)

To fix the problem, we need to ensure that the value retrieved from the `#public-scope` input element is properly sanitized before being used to set `window.location.href`. One way to achieve this is by using a safe method to encode the URL, ensuring that any potentially harmful characters are escaped.

We can use the `encodeURIComponent` function to encode the URL values before setting `window.location.href`. This function encodes special characters, making it safe to use in a URL context.

_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

### CODE REVIEW

**Comment by merlinorg** [comment]
I almost changed this earlier to...

```
<a href="{{ public_authorize_url }}">
...
$('#private-scope').click(() => $('#connect-strava').attr('href', "{{ private_authorize_url }}"));
$('#public-scope').click(() => $('#connect-strava').attr('href', "{{ public_authorize_url }}"));
```

Lets it be a real hyperlink.

**Comment by obscurerichard** [comment]
If we can specify the URLs programmatically like that, it's probably better than this autogenerated Copilot auto fix... can you amend it like that @merlinorg to let it be a real hyperlink, if that will work reliably? This is one of those where having a staging site with a different app would be useful for testing, it's hard to test this except live.

**Review by merlinorg — APPROVED** [review]
I approve this message.

**Comment by merlinorg** [comment]
@obscurerichard you can see it work locally by watching the mouse-over href as you toggle the checkboxes. Also safely falls back to public if javascript is disabled.

**Pull request merged**
